spring.application.name=server
spring.profiles.include=db,oauth

# strategy of ddl (create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true